### PR TITLE
Fixed deprecated call

### PR DESCRIPTION
**Pull request by TheOdd**
In the deprecation cop section in atom, it warned of phasing out ::this and ::shadow, etc with just calling the editor class or something along those lines. It automatically translated this line to the proper format, but that would eventually be removed so I manually fixed the deprecation for when that happens.

### CODE REVIEW

**Comment by OmarShehata** [comment]
Thanks @TheOdd ! Really excited to see a contribution to this! 

I see you've also included a Javascript implementation in this PR (which I'm really excited about and looks awesome!) but was it intentional to include both in this PR?

In any case I'll probably review and merge this later today!

**Comment by TheOdd** [comment]
@OmarShehata Whoops didn't mean to include that! You can probably just manually copy the one-liner change from the first commit to the master branch without merging this PR. I can close it now, if you'd like.

**Comment by OmarShehata** [comment]
@TheOdd actually if you'd like, you can close this PR and open one with just the deprecation code, and I can merge that (so there'll be a record of your contribution!)

**Comment by TheOdd** [comment]
@OmarShehata Sorry, but how would I make a PR with only the deprecation code? Would I have to make a separate branch?

**Comment by OmarShehata** [comment]
@TheOdd yeah the easiest thing to do would probably be make a new branch and add your commit there (but if you've already made your commits then the new branch would have those too. You could branch off of a previous commit I believe.) You could make a clean fork and just make the change there. Maybe you could also copy your files, revert the commit right now and then put them back?

**Pull request closed without merging**
